### ISSUE TITLE
Apt Mirror not mirroring bionic/main DEP-11 64x64@2 Icons  or bionic-updates/main DEP-11 64x64@2 Icons

### ISSUE THREAD

**Issue by deano2point0** [apt-mirror/apt-mirror#102]
I am running apt-mirror 0.5.4-1 on an 18.04 server.

I have 18.04 clients using this server as their package source. In the last week or so all my 18.04 clients have started getting the following error during their apt updates, 

`Err:18 http://mymirror.blah:80/ubuntu bionic/main DEP-11 64x64@2 Icons   404  Not Found [IP: *.*.*.* 80]`
`Err:64 http://mymirror.blah:80/ubuntu bionic-updates/main DEP-11 64x64@2 Icons   404  Not Found [IP: *.*.*.* 80]`

I am mirroring bionic/main and bionic-updates main and I haven't changed the config in mirrors.list at all.

**Comment by deanoroe** [comment]
Tested pointing my clients sources.list file back at archive.ubuntu.com and apt update runs without errors...

**Comment by pbirokas** [comment]
Hi, 

i have exact the same error.
It looks like the "@2" files inside the dep11 folders, wont get downloaded.
When I download them manually it works again.

```
cd <apt-mirror-home>/mirror/archive.ubuntu.com/ubuntu/dists
for dist in bionic bionic-updates bionic-security; do 
  for repo in main  multiverse universe; do
    for size in 48 64 128; do
    wget http://archive.ubuntu.com/ubuntu/dists/${dist}/${repo}/dep11/icons-${size}x${size}@2.tar.gz -O ${dist}${repo}/dep11/icons-${size}x${size}@2.tar.gz; 
   done
 done
done
```

This is just a workaround. I hope this can be fixed. 
I will take a look on the apt-mirror script and maybe find the issue.

**Comment by pbirokas** [comment]
After Review the code, I found  the line that causes the error.
I have apt-mirror (0.5.1-1) on an Ubuntu 14.04 server installed.
On line 648:
`if ( $filename =~ m{^$component/dep11/(Components-${arch}\.yml|icons-[^./]+\.tar)\.gz$} )`

**Comment by deanoroe** [comment]
My workaround was to comment out the following section of /etc/apt.apt.conf.d/50appstream but i like your workaround better!

`    # Icons suitable for HiDPI displays, for GUI components described in
    # the DEP-11 YAML metadata.
# FEPS: temporarily commented out to fix DEP-11 icons apt update issue    
#    deb::DEP-11-icons-hidpi  {
#        MetaKey "$(COMPONENT)/dep11/icons-64x64@2.tar";
#        ShortDescription "icons-64x64@2";
#        Description "$(RELEASE)/$(COMPONENT) DEP-11 64x64@2 Icons";
#
#        KeepCompressed "true";
#        KeepCompressedAs "gz";
#        DefaultEnabled "false";
#    };`

That regex looks sound to me, maybe you should consider making a pull request??

**Comment by zachwelch** [comment]
This is a real problem, but the regular expression is not the correct solution. As I noted on PR #103, the ``@2`` files appear in the URL lists being passed to wget, and the logs show that the files are being retrieved.

From what I can tell, wget internally rewrites ``icon-NxN@2.tar.gz`` as ``icon-NxN.tar.gz``. The contents of the later then end up being racy; some files have the correct contents, while others have the contents of the ``@2`` files.

**Comment by zachwelch** [comment]
So, `wget` has been cleared; here's the buggy line in ``apt-mirror``:
```
sub sanitise_uri
{
    ...
    $uri =~ s/^([^@]+)?@?// if $uri =~ /@/;
    ...
}
```
All of the URLs are sanitized to remove the `@2`, and that function is called to build the names of files to copy from the `skel` to `mirror`. Thus, no `@2` files can make it.

Remove that line and the missing files suddenly appear where they belong.

**Comment by byPhyl** [comment]
I have a similar issue with a 48x48 icon file and just tried this workaround which does not work. I'll try to find time to dig in. Thank you for pointing all of this, it helps :)

**Comment by Memphizzz** [comment]
I have the same issue, which workaround is recommended until a fix is released?

**Comment by colttt** [comment]
The uri fix doesn't work for me.
But in my case it looks that apt-mirror doesn't try to download it

**Comment by colttt** [comment]
The uri fix doesn't work for me.
But in my case it looks that apt-mirror doesn't try to download it

**Comment by bodaay** [comment]
Suggested Script to solve:
https://github.com/apt-mirror/apt-mirror/issues/113

**Comment by Sicnus** [comment]
zachwelch's fix worked for us.  We had the same problem.

**Comment by alowther** [comment]
I came across this after submitting #124.  I created a simple patch that appears to fix the issue for me.  I think the assumption is that the **@** symbol would only appear for repositories that require credentials.  A file name with the **@** symbol would break the sanitise_uri logic

[dep11.txt](https://github.com/apt-mirror/apt-mirror/files/3278370/dep11.txt)

**Comment by xapaxuc** [comment]
> cd <apt-mirror-home>/mirror/archive.ubuntu.com/ubuntu/dists
> for dist in bionic bionic-updates bionic-security; do 
>   for comp in main  multiverse universe; do
>     for size in 48 64 128; do
>     wget http://archive.ubuntu.com/ubuntu/dists/${dist}/${comp}/dep11/icons-${size}x${size}@2.tar.gz -O ${dist}${comp}/dep11/icons-${size}x${size}@2.tar.gz; 
>    done
>  done
> done

small fix: 
wget http://archive.ubuntu.com/ubuntu/dists/${dist}/${comp}/dep11/icons-${size}x${size}@2.tar.gz -O ${dist}/${comp}/dep11/icons-${size}x${size}@2.tar.gz;

**Comment by flavienbwk** [comment]
I've merged all pull requests in [flavienbwk/apt-mirror-docker](https://github.com/flavienbwk/apt-mirror-docker), enjoy !

You may consider using [debmirror](https://github.com/flavienbwk/debmirror) as well, that seem a bit more robust

**Comment by sivsko1000** [comment]
@flavienbwk 
apt-mirror supports releases after Bionic, but debmirror have problems with Eoan and Focal.
and apt-mirror have the support of multi threads download.

**Comment by TMUniversal** [comment]
> Hi,
> 
> i have exact the same error. It looks like the "@2" files inside the dep11 folders, wont get downloaded. When I download them manually it works again.
> 
> ```bash
> cd <apt-mirror-home>/mirror/archive.ubuntu.com/ubuntu/dists
> for dist in bionic bionic-updates bionic-security; do 
>   for comp in main  multiverse universe; do
>     for size in 48 64 128; do
>       wget http://archive.ubuntu.com/ubuntu/dists/${dist}/${comp}/dep11/icons-${size}x${size}@2.tar.gz -O ${dist}/${comp}/dep11/icons-${size}x${size}@2.tar.gz; 
>     done
>   done
> done
> ```
> 
> This is just a workaround. I hope this can be fixed. I will take a look on the apt-mirror script and maybe find the issue.

Thank you for this, I've used this script (with the fix from https://github.com/apt-mirror/apt-mirror/issues/102#issuecomment-593127153) in my `<apt-mirror-home>/var/postmirror.sh`

**Comment by PhotonQuantum** [comment]
#156 didn't fix the problem completely. `@2` files are downloaded but not copied from skel to mirror directory.
https://github.com/apt-mirror/apt-mirror/pull/103#issuecomment-894619043 fixes this.

**Comment by chutzimir** [comment]
> #156 didn't fix the problem completely. `@2` files are downloaded but not copied from skel to mirror directory. [#103 (comment)](https://github.com/apt-mirror/apt-mirror/pull/103#issuecomment-894619043) fixes this.

@PhotonQuantum Can you show an example of how this is not working? I just deleted the `dists/jammy` directory and did a fresh download with the following configuration:

```
deb [arch=amd64] http://archive.ubuntu.com/ubuntu     jammy           main restricted universe multiverse main/debian-installer
```

and I did get the appropriate files in the newly created `jammy` directory:

```
 $ find jammy/ -name \*@2\* -exec ls -go {} +
-rw-rw-r-- 4 29238 Apr  9  2022 jammy/main/dep11/icons-128x128@2.tar.gz
-rw-rw-r-- 4 10970 Apr  9  2022 jammy/main/dep11/icons-48x48@2.tar.gz
-rw-rw-r-- 4 15828 Apr  9  2022 jammy/main/dep11/icons-64x64@2.tar.gz
-rw-rw-r-- 4   904 Nov  2  2021 jammy/multiverse/dep11/icons-128x128@2.tar.gz
-rw-rw-r-- 4   215 Nov  2  2021 jammy/multiverse/dep11/icons-48x48@2.tar.gz
-rw-rw-r-- 4   214 Nov  2  2021 jammy/multiverse/dep11/icons-64x64@2.tar.gz
-rw-rw-r-- 4 67673 Apr  9  2022 jammy/universe/dep11/icons-128x128@2.tar.gz
-rw-rw-r-- 4 52590 Apr  9  2022 jammy/universe/dep11/icons-48x48@2.tar.gz
-rw-rw-r-- 4 69255 Apr  9  2022 jammy/universe/dep11/icons-64x64@2.tar.gz
```

I cannot reproduce using the latest version in this repo.

**Comment by chutzimir** [comment]
> > #156 didn't fix the problem completely. `@2` files are downloaded but not copied from skel to mirror directory. [#103 (comment)](https://github.com/apt-mirror/apt-mirror/pull/103#issuecomment-894619043) fixes this.
> 
> @PhotonQuantum Can you show an example of how this is not working? I just deleted the `dists/jammy` directory and did a fresh download with the following configuration:
> 
> ```
> deb [arch=amd64] http://archive.ubuntu.com/ubuntu     jammy           main restricted universe multiverse main/debian-installer
> ```
> 
> and I did get the appropriate files in the newly created `jammy` directory:
> 
> ```
>  $ find jammy/ -name \*@2\* -exec ls -go {} +
> -rw-rw-r-- 4 29238 Apr  9  2022 jammy/main/dep11/icons-128x128@2.tar.gz
> -rw-rw-r-- 4 10970 Apr  9  2022 jammy/main/dep11/icons-48x48@2.tar.gz
> -rw-rw-r-- 4 15828 Apr  9  2022 jammy/main/dep11/icons-64x64@2.tar.gz
> -rw-rw-r-- 4   904 Nov  2  2021 jammy/multiverse/dep11/icons-128x128@2.tar.gz
> -rw-rw-r-- 4   215 Nov  2  2021 jammy/multiverse/dep11/icons-48x48@2.tar.gz
> -rw-rw-r-- 4   214 Nov  2  2021 jammy/multiverse/dep11/icons-64x64@2.tar.gz
> -rw-rw-r-- 4 67673 Apr  9  2022 jammy/universe/dep11/icons-128x128@2.tar.gz
> -rw-rw-r-- 4 52590 Apr  9  2022 jammy/universe/dep11/icons-48x48@2.tar.gz
> -rw-rw-r-- 4 69255 Apr  9  2022 jammy/universe/dep11/icons-64x64@2.tar.gz
> ```
> 
> I cannot reproduce using the latest version in this repo.

Same thing with bionic:

```
deb [arch=amd64] http://archive.ubuntu.com/ubuntu     bionic main
```
gets me
```
find bionic -name \*@\* -exec ls -go {} +
-rw-r--r-- 6 29 Apr 25  2018 bionic/main/dep11/icons-128x128@2.tar.gz
-rw-r--r-- 6 29 Apr 25  2018 bionic/main/dep11/icons-48x48@2.tar.gz
-rw-r--r-- 6 29 Apr 25  2018 bionic/main/dep11/icons-64x64@2.tar.gz
```

**Comment by PhotonQuantum** [comment]
Using latest master with:
```
deb-all http://apt.pop-os.org/release jammy main
deb-amd64 http://apt.pop-os.org/release jammy main
deb-arm64 http://apt.pop-os.org/release jammy main
deb-i386 http://apt.pop-os.org/release jammy main
deb-src http://apt.pop-os.org/release jammy main
clean http://apt.pop-os.org/release
```

got skel:
```bash
$ ls skel/apt.pop-os.org/release/dists/jammy/main/dep11/
Components-amd64.yml.gz  Components-arm64.yml.gz  Components-i386.yml.gz  icons-128x128@2.tar.gz  icons-48x48@2.tar.gz  icons-64x64@2.tar.gz
Components-amd64.yml.xz  Components-arm64.yml.xz  Components-i386.yml.xz  icons-128x128.tar.gz    icons-48x48.tar.gz    icons-64x64.tar.gz
```

but, mirror:
```bash
$ ls mirror/apt.pop-os.org/release/dists/jammy/main/dep11 
Components-amd64.yml.gz  Components-amd64.yml.xz  Components-arm64.yml.gz  Components-arm64.yml.xz  Components-i386.yml.gz  Components-i386.yml.xz  icons-128x128.tar.gz  icons-48x48.tar.gz  icons-64x64.tar.gz
```

**Comment by chutzimir** [comment]
Thank you @PhotonQuantum , I submitted #177.

**Comment by james15888** [comment]
apt-mirror_0.5.4-2_all.deb fix this bug.

**Comment by james15888** [comment]
apt-mirror_0.5.4-2_all.deb fixed this bug.

**Comment by HenriWahl** [comment]
Hi there,
I run into the same problem... apparently the latest package apt-mirror either in Debian bookworm and Ubuntu 24.04 is still version 0.5.4-2, which does **not** contain the fixes shown here.
Does someone have an idea when these fixes will be in an official release?

**Comment by casual-lemon** [comment]
Hi @HenriWahl  please follow this LP for a fix in Ubuntu https://bugs.launchpad.net/ubuntu/+source/apt-mirror/+bug/2044556

**Comment by HenriWahl** [comment]
Thanks @casual-lemon, but I switched to apt-mirror2 from pypi. It is compatible to apt-mirror.

**Comment by nE0sIghT** [comment]
> apt-mirror2

Quick link: https://gitlab.com/apt-mirror2/apt-mirror2

**Comment by youssef-chtourou** [comment]
same problem for apt-mirror
