### ISSUE TITLE
Use of uninitialized value in split at /usr/bin/apt-mirror line 829

### ISSUE THREAD

**Issue by pboguslawski** [apt-mirror/apt-mirror#117]
Hi,

apt-mirror throws warning

Use of uninitialized value in split at /usr/bin/apt-mirror line 829

when parsing source index without Filename and Files like

http://security-cdn.debian.org/dists/buster/updates/main/source/Sources.gz

Please consider changing

https://github.com/apt-mirror/apt-mirror/blob/e664486a5d8947c2579e16dd793d762ea3de4202/apt-mirror#L827

like

-        else
+       elsif ( exists $lines{"Files:"} )

Regards,
Pawel

**Comment by nblock** [comment]
An `elseif` skips downloads of source files (using `deb-src …` in `mirror.list`). Another quick and dirty fix is to use the `Checksums-Sha256` section instead of the `Files` section:

```patch
--- apt-mirror.orig     2019-05-16 09:09:19.230184668 +0200
+++ apt-mirror  2019-05-16 09:09:59.207848816 +0200
@@ -826,7 +826,7 @@
         }
         else
         {    # Sources index
-            foreach ( split( /\n/, $lines{"Files:"} ) )
+            foreach ( split( /\n/, $lines{"Checksums-Sha256:"} ) )
             {
                 next if $_ eq '';
                 my @file = split;
```

This allows to at least sync Debian {Jessie, Stretch, Buster} sources.

**Comment by mrtuborg** [comment]
> An `elseif` skips downloads of source files (using `deb-src …` in `mirror.list`). Another quick and dirty fix is to use the `Checksums-Sha256` section instead of the `Files` section:
> 
> ```diff
> --- apt-mirror.orig     2019-05-16 09:09:19.230184668 +0200
> +++ apt-mirror  2019-05-16 09:09:59.207848816 +0200
> @@ -826,7 +826,7 @@
>          }
>          else
>          {    # Sources index
> -            foreach ( split( /\n/, $lines{"Files:"} ) )
> +            foreach ( split( /\n/, $lines{"Checksums-Sha256:"} ) )
>              {
>                  next if $_ eq '';
>                  my @file = split;
> ```
> 
> This allows to at least sync Debian {Jessie, Stretch, Buster} sources.

Hello from the 2022 :)
This patch is leading towards new error message:
"Use of uninitialized value $lines{"Checksums-Sha256:"} in split at /usr/bin/apt-mirror line 829"

**Comment by hiddenman** [comment]
@mrtuborg @nblock @pboguslawski  Hi guys,
Got all of these apt-mirror issues including the problem with Translations-*.

Here is my patch for them:
`--- apt-mirror	2017-05-29 00:00:00.000000000 +0300
+++ /usr/bin/apt-mirror	2023-04-18 15:48:22.967579321 +0300
@@ -520,7 +520,7 @@
                 if ( @parts == 3 )
                 {
                     my ( $sha1, $size, $filename ) = @parts;
-                    if ( $filename =~ m{^$component/i18n/Translation-[^./]*\.bz2$} )
+                    if ( $filename =~ m{^$component/i18n/Translation-[^./]*\.(bz2|xz)$} )
                     {
                         add_url_to_download( $dist_uri . $filename, $size );
                     }
@@ -824,12 +824,29 @@
                 add_url_to_download( $uri . "/" . $lines{"Filename:"}, $lines{"Size:"} );
             }
         }
-        else
+        elsif ( exists $lines{"Files:"} )
         {    # Sources index
             foreach ( split( /\n/, $lines{"Files:"} ) )
             {
                 next if $_ eq '';
                 my @file = split;
+                die("apt-mirror: invalid Sources format") if @file != 3;
+                $skipclean{ remove_double_slashes( $path . "/" . $lines{"Directory:"} . "/" . $file[2] ) } = 1;
+                print FILES_ALL remove_double_slashes( $path . "/" . $lines{"Directory:"} . "/" . $file[2] ) . "\n";
+                print FILES_MD5 $file[0] . "  " . remove_double_slashes( $path . "/" . $lines{"Directory:"} . "/" . $file[2] ) . "\n";
+                if ( need_update( $mirror . "/" . $lines{"Directory:"} . "/" . $file[2], $file[1] ) )
+                {
+                    print FILES_NEW remove_double_slashes( $uri . "/" . $lines{"Directory:"} . "/" . $file[2] ) . "\n";
+                    add_url_to_download( $uri . "/" . $lines{"Directory:"} . "/" . $file[2], $file[1] );
+                }
+            }
+        }
+        elsif ( exists $lines{"Checksums-Sha256:"} )
+        {    # Sources index
+            foreach ( split( /\n/, $lines{"Checksums-Sha256:"} ) )
+            {
+                next if $_ eq '';
+                my @file = split;
                 die("apt-mirror: invalid Sources format") if @file != 3;
                 $skipclean{ remove_double_slashes( $path . "/" . $lines{"Directory:"} . "/" . $file[2] ) } = 1;
                 print FILES_ALL remove_double_slashes( $path . "/" . $lines{"Directory:"} . "/" . $file[2] ) . "\n";
`

**Comment by chutzimir** [comment]
I cannot reproduce this issue with the latest version in the master branch and this line in the configuration file:

```
deb-src http://security-cdn.debian.org buster/updates main
```

Are there any examples of mirrors which have this problem?

**Comment by hiddenman** [comment]
@chutzimir I've got these problems with these sources:

`
deb-amd64 http://deb.debian.org/debian bullseye main main/debian-installer contrib non-free
deb-src http://deb.debian.org/debian bullseye main contrib non-free

deb-amd64 http://security.debian.org/debian-security bullseye-security main main/debian-installer contrib non-free
deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free

deb-amd64 http://deb.debian.org/debian bullseye-updates main main/debian-installer contrib non-free
deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

deb-amd64  http://deb.debian.org/debian bullseye-backports main main/debian-installer contrib non-free
deb-src  http://deb.debian.org/debian bullseye-backports main contrib non-free

`

**Comment by chutzimir** [comment]
Aha, thank you. It seems that PR#163 already fixed this issue - it checks for any of Checksums-Sha512, Checksums-Sha256, Checksums-Sha1, or Files and uses whatever is available. Do you want to give it a try?

**Comment by hiddenman** [comment]
> Aha, thank you. It seems that #163 already fixed this issue - it checks for any of Checksums-Sha512, Checksums-Sha256, Checksums-Sha1, or Files and uses whatever is available. Do you want to give it a try?

@chutzimir Hi.
Where do i get the latest version to check everything? Current release 0.5.4 is old. Should i use git latest version from master?

**Comment by hiddenman** [comment]
@chutzimir I've got another strange problem., not sure why this happens (it used to work without any issues; looks like updating to Sid caused this:)

1. I'm mirroring only deb-amd64 release
2. However, when i use apt update, i always get missing Contents-all files. not sure why apt wants them to exist:

```
E: Failed to fetch http://xxx/debian/dists/bullseye/main/Contents-all  404  Not Found [IP: x.y.z.z 80]
E: Failed to fetch http://xxx/debian/dists/bullseye-updates/main/Contents-all  404  Not Found [IP: x.y.z.z 80]
```
Checked the source code and didn't get how (and why) to fetch Contents-all files.

**Comment by chutzimir** [comment]
> > Aha, thank you. It seems that #163 already fixed this issue - it checks for any of Checksums-Sha512, Checksums-Sha256, Checksums-Sha1, or Files and uses whatever is available. Do you want to give it a try?
> 
> @chutzimir Hi. Where do i get the latest version to check everything? Current release 0.5.4 is old. Should i use git latest version from master?

@hiddenman The 0.5.4 is indeed very old, and a lot of fixes were merged into the Git master. Using the latest Git master is currently recommended, considering how many issues were resolved since 0.5.4.

This fix for this issue, however, was resolved by pull request #163 which is **not merged** to master yet (though it is tagged for inclusion in the next release 0.6.0). I was suggesting that you take the `apt-mirror` version from that pull request and try it out. You can either download the file from the pull request or use this link to get the version that would be merged into master when #163 gets accepted: https://raw.githubusercontent.com/apt-mirror/apt-mirror/395e01d7490bc04e254094ef81489767b3cc387f/apt-mirror

**Comment by tiix95** [comment]
Hi,

Would this be merged into master soon ? What is the ETA for release 0.6.0 ?

Thank you very much

**Comment by chutzimir** [comment]
@SupaHiro I hope you are OK. Can you chime in on plans to merge some of the open PRs?

**Comment by SupaHiro** [comment]
Hey @chutzimir , apologies that I have not gotten to the remaining  PRs. Let me see what I can get done over the next few weeks!

**Comment by pcoreyster** [comment]
As it has been over 1 year since the last post on this thread, the merge occurred on 1 Nov 2023.
As I am using Debian 12's apt-mirror module, I saw the version is 0.5.4-2.    While this reported issue still occurs, I wanted to ask again for any new ETA for the 0.6.0 release?

**Comment by nE0sIghT** [comment]
@pcoreyster 

Please look to the https://github.com/apt-mirror/apt-mirror/issues/139

**Comment by pcoreyster** [comment]
@nE0sIghT 
Thank you I am watching that thread now.
