### ISSUE TITLE
New Mozilla apt repo does not work with apt-mirror

### ISSUE THREAD

**Issue by lazywebm** [apt-mirror/apt-mirror#187]
Tried setting up a mirror for the new Mozilla apt repo following their recent announcement [1], but it's failing with an error. The problem seems to be a trailing slash being added to the repo URL.

Config:

`deb [arch=amd64] https://packages.mozilla.org/apt mozilla main`

Error:

`Processing indexes: [PPPPPPPPPPPPPPPPPPPPPapt-mirror: can't open index packages.mozilla.org/apt//dists/mozilla/main/binary-amd64/Packages in process_index at /usr/bin/apt-mirror line 864.
`

Tried with with the last official release (v0.5.4) installed via apt on Debian stable, as well as the drop-in replacement from the master branch here, as of 2024-01-25.

[1] https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions

**Comment by nE0sIghT** [comment]
This is because of https://github.com/apt-mirror/apt-mirror/commit/76bd728ec6e799073183622ea13c3ca9b4f65e82  
The comment states `I cannot find a single repository serving the uncompressed index files`, so we found one :-)

I fixed this in the [apt-mirror2](https://gitlab.com/apt-mirror2/apt-mirror2/-/merge_requests/35)

**Comment by lazywebm** [comment]
Ah, thanks for the hint. I've manually reverted [76bd728](https://github.com/apt-mirror/apt-mirror/commit/76bd728ec6e799073183622ea13c3ca9b4f65e82) on my system, which works too.

**Comment by kenyon** [comment]
Same problem with ddebs.ubuntu.com: https://wiki.ubuntu.com/Debug%20Symbol%20Packages

**Comment by lazywebm** [comment]
Following up on my comment from my comment above, the manual revert did not fix the issue. Doing an "apt update" on a system where I added my Mozilla repo mirror yields this error:

```
Get:12 https://aptmirror.example.com/mozilla/apt mozilla/main amd64 Packages [81,4 kB]
Err:12 https://aptmirror.example.com/mozilla/apt mozilla/main amd64 Packages
  File has unexpected size (65113 != 81391). Mirror sync in progress? [IP: xxx.xxx.xxx.xxx]
  Hashes of expected file:
   - Filesize:81391 [weak]
   - SHA256:0f0566d8ac81be981bc41771ad2e2fc8640cf383cfce0109acbd84b95605bc73
   - MD5Sum:2f66ff5102fb43fbba4367c28209da4f [weak]
  Release file created at: Wed, 13 Mar 2024 00:19:53 +0000
Get:13 https://aptmirror.example.com/mozilla/apt mozilla/main all Packages [4.517 kB]
Err:13 https://aptmirror.example.com/mozilla/apt mozilla/main all Packages
  
Reading package lists... Done
E: Failed to fetch https://aptmirror.example.com/mozilla/apt/dists/mozilla/main/binary-amd64/Packages  File has unexpected size (65113 != 81391). Mirror sync in progress? [IP: xxx.xxx.xxx.xxx] 
   Hashes of expected file:
    - Filesize:81391 [weak]
    - SHA256:0f0566d8ac81be981bc41771ad2e2fc8640cf383cfce0109acbd84b95605bc73
    - MD5Sum:2f66ff5102fb43fbba4367c28209da4f [weak]
   Release file created at: Wed, 13 Mar 2024 00:19:53 +0000
E: Failed to fetch https://aptmirror.example.com/mozilla/apt/dists/mozilla/main/binary-all/Packages  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by nE0sIghT** [comment]
@lazywebm 
This is another issue which is not specific for Mozilla repo, but exists for all repos.  
It's architectural problem which can not be easy fixed in the apt-mirror AFAIK.  

It's fixed in the apt-mirror2 which controls repository consistency.

**Comment by lazywebm** [comment]
Thanks for pointing that out, made it work with apt-mirror2.
